version: '3.7'

services:
  tines-app:
    image: nginx:alpine
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./app/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000"  # 此端口只用于本地测试，实际部署中应由 Nginx 控制访问
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - tines-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

