global:
  scrape_interval: 30s
  scrape_timeout: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: node
   static_configs:
    - targets:
       - node-exporter:9100
    - targets: [ '127.0.0.1:9100' ]
      labels:
        instance: 'local-vm'
        # service: 'local-vm'
