version: '3'

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    restart: always
    volumes:
      - drone-data:/data
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=ci.zouying.work
      - DRONE_SERVER_PROTO=https
    ports:
      - "8080:80"  # 只暴露HTTP端口，映射到8080
    networks:
      - drone-network

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PORT=80
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge

volumes:
  drone-data:
