version: "3.8"

services:
  bark-server:
    image: finab/bark-server
    container_name: bark-server
    restart: unless-stopped
    volumes:
      - ./container-data:/data
    networks:
      zy-network:

networks:
  zy-network:
    external: true
