version: '3'

services:
  headscale:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:
      - ./container-config:/app/data
    networks:
      headscale-network:


networks:
  headscale-network:
    external: true